# Generated by Django 5.2.14 on 2026-05-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='fileNo')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='原始檔名')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME 類型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='檔案大小 (bytes)')),
                ('storage_path', models.CharField(help_text='本機路徑或 S3 key', max_length=500, verbose_name='儲存路徑')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('uploaded_by_session', models.CharField(blank=True, default='', max_length=100, verbose_name='上傳者 session')),
            ],
            options={
                'verbose_name': '上傳檔案',
                'verbose_name_plural': '上傳檔案清單',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiFakeCode',
            fields=[
                ('code', models.CharField(help_text='探頭上印的防偽碼字串，例如 YK6Z0VXAG8G8', max_length=50, primary_key=True, serialize=False, verbose_name='防偽碼')),
                ('verify_count', models.PositiveIntegerField(default=0, help_text='消費者掃描查驗的累計次數。第一次驗證為 1、N≥2 顯示有疑慮警語', verbose_name='驗證次數')),
                ('is_active', models.BooleanField(default=True, help_text='關閉後查詢仍會顯示計數、但不再增加', verbose_name='啟用中')),
                ('first_verify_at', models.DateTimeField(blank=True, null=True, verbose_name='首次驗證時間')),
                ('last_verify_at', models.DateTimeField(blank=True, null=True, verbose_name='最近驗證時間')),
                ('notes', models.TextField(blank=True, default='', help_text='批次號 / 產品 SKU / 出貨對象等業主自由備註', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
            options={
                'verbose_name': '防偽碼',
                'verbose_name_plural': '防偽碼清單',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verify_count'], name='idx_verify_count'), models.Index(fields=['last_verify_at'], name='idx_last_verify_at'), models.Index(fields=['is_active'], name='idx_is_active')],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.TextField(blank=True, default='', help_text='前端送來的 questObjectList 原始 JSON', verbose_name='回答內容 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to='antifake.antifakecode', verbose_name='對應防偽碼')),
            ],
            options={
                'verbose_name': '問卷回應',
                'verbose_name_plural': '問卷回應清單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplementReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(blank=True, default='', help_text='格式：王小明/09XXXXXXXX', max_length=100, verbose_name='聯絡資訊')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antifake.uploadedfile', verbose_name='上傳照片')),
            ],
            options={
                'verbose_name': '補件回報',
                'verbose_name_plural': '補件回報清單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否為會員')),
                ('legal_name', models.CharField(blank=True, default='', max_length=40, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='電子信箱')),
                ('country_code', models.CharField(blank=True, default='', max_length=5, verbose_name='國際區號')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手機')),
                ('sex', models.CharField(blank=True, default='', max_length=1, verbose_name='性別')),
                ('prod_seq', models.CharField(blank=True, default='', max_length=50, verbose_name='商品防偽碼')),
                ('prob_type', models.CharField(blank=True, choices=[('1', '假冒產品'), ('2', '產品問題'), ('3', '其他')], default='', max_length=5, verbose_name='問題類型')),
                ('pur_country', models.CharField(blank=True, default='', max_length=20, verbose_name='購買國家')),
                ('pur_city', models.CharField(blank=True, default='', max_length=50, verbose_name='購買縣市')),
                ('store_type', models.CharField(blank=True, default='', max_length=5, verbose_name='商店分類')),
                ('pur_store', models.CharField(blank=True, default='', max_length=50, verbose_name='購買商店')),
                ('pur_date', models.DateField(blank=True, null=True, verbose_name='購買日期')),
                ('pur_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='購買金額')),
                ('pur_price_currency', models.CharField(blank=True, default='', max_length=5, verbose_name='幣別')),
                ('prob_desc', models.TextField(blank=True, default='', verbose_name='問題描述')),
                ('agree_to_terms', models.BooleanField(default=False, verbose_name='同意條款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antifake.uploadedfile', verbose_name='附件')),
            ],
            options={
                'verbose_name': '聯絡我們',
                'verbose_name_plural': '聯絡我們清單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_at', models.DateTimeField(auto_now_add=True, verbose_name='驗證時間')),
                ('verify_count_snapshot', models.PositiveIntegerField(default=0, help_text='該次驗證時的累計 N 值', verbose_name='當次驗證次數')),
                ('client_ip', models.CharField(blank=True, default='', max_length=45, verbose_name='消費者 IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='瀏覽器 UA')),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='緯度')),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='經度')),
                ('geo_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='定位精度')),
                ('auth_token', models.CharField(blank=True, default='', max_length=100, verbose_name='auth token')),
                ('request_info_id', models.CharField(blank=True, default='', max_length=100, verbose_name='requestInfoId')),
                ('code', models.ForeignKey(blank=True, help_text='查驗的碼（若已被刪除則為 null）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='antifake.antifakecode', verbose_name='防偽碼')),
            ],
            options={
                'verbose_name': '驗證記錄',
                'verbose_name_plural': '驗證歷史',
                'ordering': ['-verify_at'],
                'indexes': [models.Index(fields=['code', 'verify_at'], name='idx_code_verify_at'), models.Index(fields=['verify_at'], name='idx_verify_at')],
            },
        ),
    ]
