# Generated by Django 5.2.14 on 2026-05-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='設定鍵')),
                ('value', models.TextField(verbose_name='設定值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='說明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='contactticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplementreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
