# Generated by Django 5.2.14 on 2026-05-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antifake', '0002_systemconfig_alter_contactticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antifakecode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刪除時間'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='設定值'),
        ),
    ]
